trainer: energy

dataset:
  - src: explo/is2re/10k/train/explo.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
  - src: explo/is2re/all/val_id/explo.lmdb

logger: tensorboard

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
